import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          HUNTING CODER
        </h1>

        <div className={styles.imagewrap}>
          <Image className={styles.myImg} src='/Coder1.jpg' alt='icon' width={240} height={160} />
        </div>
        <p className={styles.description}>
          A Blog for hunting coders by a hunting coder.
        </p>

        <h2 className={styles.code}>Popular Blogs</h2>
        <div className={styles.grid}>
          <a href='https://www.w3schools.com/js/' className={styles.card}>
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </a>
          <a href='https://www.python.org/' className={styles.card}>
            <h3>How to learn Python in 2022?</h3>
            <p>Python is the language used to design logic for the web</p>
          </a>
          <a href='https://reactjs.org/' className={styles.card}>
            <h3>How to learn Reactjs in 2022?</h3>
            <p>Reactjs is the language used to design logic for the web</p>
          </a>
          <a href='https://nodejs.org/en/' className={styles.card}>
            <h3>How to learn Nodejs in 2022?</h3>
            <p>Nodejs is the language used to design logic for the web</p>
          </a>
        </div>
      </main>

     
    </div>
  )
}

export default Home
